### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by Athena9355** [Athena9355/Team-123-final-version#12]
**Scrum Team GitHub pages (2 points)**

- [x] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license

- [x] [1st Code in GitHub with software license per 5.5](https://github.com/Athena9355/Team-123-final-version/pull/13)

**Comment by suneelanaidu** [comment]
Sponsor - Mr West.
Using MIT License
