### ISSUE TITLE
AN Accounts and Logins Review Ticket (Athena)

### ISSUE THREAD

**Issue by Athena9355** [Athena9355/Team-123-final-version#14]
**CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)**
- [ ] [CB Create Task Coding requirements documented](https://athena9355.github.io/Tri3-Data-Structure/cb)
- [ ] Runtime of [Code](https://github.com/Athena9355/Tri3-Data-Structure/blob/main/mathy.py)(with comments) on Replit/Intellij

**Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)**
- [ ] Hack 1 Add [Phone](https://github.com/Athena9355/Team-123-final-version/commit/e0dac78598cc089159592dcbb8a050354965ded5) Number to Sign Up / Authorization screen
- [ ] Hack 2 Add [logout](https://github.com/Athena9355/Team-123-final-version/commit/5f27c93e9aadbbeba4226280a0b8ad2309e35710) to CRUD screen
- [ ] Hack 3 [Add login_required to another portion of the project](https://github.com/Athena9355/Team-123-final-version/commit/b3feedd6323bf195fbf7a1485936e10e46a1e32d)

**Comment by xu-ellen** [comment]
Total score: 4.5/5
Crossover grader: Ellen

CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
CB Create Task Coding requirements documented - **1/1** documented Create task requirements for hangman
Runtime of Code(with comments) on Replit/Intellij - **1/1** showed hangman runtime and working code
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio) - **2.5/3** had all 3 Hacks and showed working runtime; -0.5 for missing analysis answer
Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
Hack #1 Add Phone Number to Sign Up / Authorization screen
Hack #2 Add logout to CRUD screen
Hack #3 Add login_required to another portion of the project
Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
